# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Family Tree application integrity test

on:
  push:
    branches:
      - naman
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt
        pip install python-dateutil
        pip install PrettyTable
    - name: Run user stories automated tests
      run: |
        python -m com.familytree.tests.stories_test_suite
        python run_app.py
